name: Flatpak
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
    flatpak:
      name: "Flatpak"
      runs-on: ubuntu-latest
      container:
        image: bilelmoussaoui/flatpak-github-actions:gnome-45
        options: --privileged
      steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install libfido2-dev
        run: sudo apt-get install -y libfido2-dev
      - name: Build
        run: go build -o goldwarden -v .
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: goldwarden.flatpak
          manifest-path: com.quexten.Goldwarden.yml
          cache-key: flatpak-builder-${{ github.sha }}